### ISSUE TITLE
Server?!

### ISSUE THREAD

**Issue by idkjs** [Steinarthor/codex#3]
Hey brother. Thank you for sharing this. I think you are about to help me understand something. Is the server you are using available somewhere?

Thank you.

And I love your country!

**Comment by Steinarthor** [comment]
Oh hello! No problem, It was just me playing around, nothing special 😸. Hmm, the server is just a simple JS server https://github.com/Steinarthor/codex-graphql 

🇮🇸 is marvellous 🙏

**Comment by idkjs** [comment]
The graphql link is a dead link, sir. Yes, I was referring to the graphql server. I wanted to inspect the response here to try to understand what is happening there:

https://github.com/Steinarthor/codex/blob/7088e10fb6425e543e981c309e5d3ef22bf1cfc2/src/Apollo.re#L22-L28

Thank you, sir.

**Comment by Steinarthor** [comment]
Ahh I see, no problem. Here's the link to the graphl sandbox repo: https://github.com/Steinarthor/codex-graphql

Basically what's happening is I'm mapping over Apollo´s `errorExtensions` array.

On graphQL side I throw `AuthenticationError` that returns `error.code = UNAUTHENTICATED` ofc this is just to play with and not ideal way to handle authentication. You can read more about Apollo error handling here: https://www.apollographql.com/docs/apollo-server/data/errors/

Have a nice day 🎉

**Comment by idkjs** [comment]
Thank you, sir, for the link and the explanation. This has been very helpful for me. Thank you for sharing your code.

**Comment by idkjs** [comment]
Just to complete the example, do you have this guy laying around->

https://github.com/Steinarthor/codex-graphql/blob/master/datasources/auth.js

Its the auth server you are using. Thank you, sir.

**Comment by Steinarthor** [comment]
Sure! It's written in Go, hope that's fine. https://github.com/Steinarthor/codex-api

**Comment by idkjs** [comment]
Thank you, sir!

**Comment by idkjs** [comment]
Here is a random question for you. I see you worked at WowAir. Do you know if any of that code has been open sourced since the company closed down? I have been checking on that for a while now.

**Comment by Steinarthor** [comment]
I'm afraid that it's not open sourced.
